import Navbar from '@/components/navbar/Navbar';
import { Toaster } from '@/components/ui/toaster';
import { Profile } from '@/lib/profile';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const profile = await Profile();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar profile={profile} />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
